"""
Django settings for merchant project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t9wggpmu6lz0teqdlz%ss%37&#t*k(4k%!5vfu3xz_m2=e_kt$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','aman-merchant.uniparticle.com','10.50.110.5']
CSRF_TRUSTED_ORIGINS=['amanaccept.com']
DEV = False
# DEV = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts_manager',
    'analytics',
    'helpers',
    'rest_framework',
    'drf_yasg2',
    'rest_framework.authtoken',
    'notification_manager',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'merchant.middleware.corsMiddleware.CORSMiddleware',
]

ROOT_URLCONF = 'merchant.urls'

PAGINATION_PAGE_SIZE=10

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'merchant.wsgi.application'

REST_FRAMEWORK = {
    # 'DATETIME_FORMAT': "%B %d, %Y",
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'accounts_manager.authentication.token_authentication.ExpiringTokenAuthentication'
    ),
    'DEFAULT_PERMESSION_CLASSES': ('rest_framework.permessions.IsAuthenticated',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12
}

AUTH_TOKEN_VALIDITY = getattr(settings, 'AUTH_TOKEN_VALIDITY', timedelta(days=7))
AUTH_USER_MODEL = 'accounts_manager.Account'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} if DEV else {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'merchantsdb',
        # 'USER': 'uniparticle',
        'USER': 'root',
        # 'PASSWORD': 'Uni@12345',
        'PASSWORD': 'root',
        # 'HOST': '10.50.140.16',
        'HOST': '127.0.0.1',
        # 'PORT': '6605',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, "staticfiles")]

OTP_EXPIRATION_TIME = 3600

SMS_SENDER_NAME = 'AMAN'
SMS_ACCOUNT_ID = '200002632'
SMS_API_PASSWORD = 'Vodafone.1'
SMS_SECRET_KEY = '7D40930F48F1480A90362BFACFBAA364'

TOKEN_LIFE_TIME = 30


#AMAN_API_URL = 'https://10.50.70.5:8443/merchantDashboard/' #STAGE
AMAN_API_URL = 'https://10.50.100.2:8443/merchantDashboard/' #PROD

PAGE_SIZE = 1

STATIC_ROOT = f'/accept-dash/static/'
STATIC_URL = f'/accept-dash/static/'

